# Generated by Django 3.2.5 on 2021-10-21 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='webapp/images')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=6)),
                ('first', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('images', models.ImageField(blank=True, null=True, upload_to=webapp.models.user_directory_path)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feed', models.CharField(choices=[('Bug', 'Bug'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=30)),
                ('Suggestion', models.CharField(max_length=500)),
                ('Star', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('vid', models.CharField(max_length=10, null=True)),
                ('Person_name', models.CharField(max_length=100, null=True)),
                ('Contact', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=webapp.models.gen_candidate_id, max_length=10)),
                ('Profile_pic', models.ImageField(upload_to=webapp.models.user_directory_path)),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=40)),
                ('Occupation_type', models.CharField(max_length=40)),
                ('Occupation_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('Education_title', models.CharField(max_length=20)),
                ('Education_area', models.CharField(max_length=200)),
                ('Hobby', models.CharField(max_length=500)),
                ('About', models.CharField(max_length=500)),
                ('Marital_st', models.CharField(max_length=30)),
                ('Height', models.FloatField()),
                ('Blood_group', models.CharField(max_length=30)),
                ('Birth_name', models.CharField(max_length=50)),
                ('Birth_time', models.CharField(max_length=30)),
                ('Birth_place', models.CharField(max_length=50)),
                ('Mother_tong', models.CharField(max_length=30)),
                ('Complexion', models.CharField(max_length=30)),
                ('Annual_income', models.CharField(max_length=30)),
                ('First_gotra', models.CharField(max_length=30)),
                ('Second_gotra', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=30)),
                ('Postal_code', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_1', models.BigIntegerField()),
                ('Contact_1_name', models.CharField(max_length=100)),
                ('Contact_1_relation', models.CharField(max_length=30)),
                ('Contact_2', models.BigIntegerField()),
                ('Contact_2_name', models.CharField(max_length=100)),
                ('Contact_2_relation', models.CharField(max_length=30)),
                ('Family', models.CharField(max_length=30)),
                ('Fathers_name', models.CharField(max_length=150)),
                ('Fathers_occupation', models.CharField(max_length=100)),
                ('Mothers_name', models.CharField(max_length=150)),
                ('Mothers_occupation', models.CharField(max_length=100)),
                ('Number_brother', models.IntegerField()),
                ('Brother_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('Number_sister', models.IntegerField()),
                ('Sister_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('Partner_compx', models.CharField(max_length=100)),
                ('Partner_occupation', models.CharField(max_length=100)),
                ('Preffered_city', models.CharField(max_length=100)),
                ('Partner_agefrom', models.IntegerField()),
                ('Partner_ageto', models.IntegerField()),
                ('Partner_height', models.FloatField()),
                ('Partner_income', models.CharField(max_length=50)),
                ('Partner_qualification', models.CharField(max_length=100)),
                ('Approval', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10)),
                ('Member', models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium')], default='Normal', max_length=10)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
