from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('verify/<auth_token>', views.verify, name='verify token'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='webapp/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='webapp/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='webapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='webapp/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('new_profile', views.new_profile, name='new_profile'),
    path('favorite', views.favorite, name='favorite'),
    path('favorite_profile', views.favorite_profile, name='favorite profile'),
    path('favorites', views.favorites, name='all favorites'),
    path('remove', views.remove, name='remove fav'),
    path('profile', views.profile, name='profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('update', views.update, name='update'),
    path('search', views.search, name='search'),
    path('can_search', views.can_search, name='candidate search'),
    path('view_profile', views.view_profile, name='view_profile'),
    path('gallery', views.gallery, name='gallery'),
    path('events', views.events, name='events'),
    path('event_enroll', views.event_enroll, name='event_enroll'),
    path('myevents', views.myevents, name='myevents'),
    path('event_detail', views.event_detail, name='event details'),
    path('event_cansearch', views.event_cansearch, name='event cansearch'),
    path('notifications', views.notification, name='notifications'),
    path('matches', views.matches, name='matches'),
    path('export_profile', views.export_profile, name='export profile'),
    path('contact', views.contact, name='contact'),
    path('feedback', views.feedback, name='feedback'),
    path('file_upload', views.file_upload, name='file upload'),
    path('delete_img', views.delete_img, name='delete image'),
    path('approval', views.approval, name='user approval'),
    path('approval_update', views.update_approval, name='update approval'),
    path('user_approve', views.user_approve, name='user approve'),
    path('forebook', views.forebook, name='for ebook'),
    path('generate', views.generate, name='generate ebook'),

]
